//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorDeVendas
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsPedidosClientes
    {
        public int CodItemPedido { get; set; }
        public int Quantidade { get; set; }
        public int CodProduto { get; set; }
        public int CodPedidoCliente { get; set; }
    
        public virtual Produtos Produtos { get; set; }
        public virtual PedidoClientes PedidoClientes { get; set; }
    }
}
