//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorDeVendas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Parcelas> Parcelas { get; set; }
        public virtual DbSet<PedidoClientes> PedidoClientes { get; set; }
        public virtual DbSet<PedidoFornecedores> PedidoFornecedores { get; set; }
        public virtual DbSet<Produtos> Produtos { get; set; }
        public virtual DbSet<ItemsPedidosClientes> ItemsPedidosClientes { get; set; }
        public virtual DbSet<ItemsPedidosFornecedor> ItemsPedidosFornecedor { get; set; }
    }
}
