//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorDeVendas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parcelas
    {
        public int CodParcela { get; set; }
        public decimal Valor { get; set; }
        public System.DateTime DtPagamento { get; set; }
        public Nullable<int> CodPedidoForncedor { get; set; }
        public Nullable<int> CodPedidoCliente { get; set; }
        public string Status { get; set; }
    
        public virtual PedidoClientes PedidoClientes { get; set; }
        public virtual PedidoFornecedores PedidoFornecedores { get; set; }
    }
}
