//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorDeVendas
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoFornecedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PedidoFornecedores()
        {
            this.Parcelas = new HashSet<Parcelas>();
            this.ItemsPedidosFornecedor = new HashSet<ItemsPedidosFornecedor>();
        }
    
        public int CodPedidoF { get; set; }
        public decimal ValorTotal { get; set; }
        public int TotalParcelas { get; set; }
        public string Status { get; set; }
        public System.DateTime Data { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parcelas> Parcelas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsPedidosFornecedor> ItemsPedidosFornecedor { get; set; }
    }
}
