//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorDeVendas
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoClientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PedidoClientes()
        {
            this.ItemsPedidosClientes = new HashSet<ItemsPedidosClientes>();
            this.Parcelas = new HashSet<Parcelas>();
        }
    
        public int CodPedidoC { get; set; }
        public int CodCliente { get; set; }
        public decimal ValorTotal { get; set; }
        public int TotalParcelas { get; set; }
        public string Status { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsPedidosClientes> ItemsPedidosClientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parcelas> Parcelas { get; set; }
    }
}
